Fix the error of getting request parameters
typecho/typecho pull request #1464
Opened 2022-06-15 11:16 UTC by sy-records

2022-06-16 04:03 UTC, joyqi reviewed
这里的替换有什么原因么，从request里面读取和直接读取应该没有区别

2022-06-16 04:06 UTC, sy-records commented
之前修复xmlrpc的时候改了这里，而在#1461中测试的时候发现无法从request中获取到参数

2022-06-16 04:17 UTC, joyqi commented
需要跟踪代码深入调查一下这里无法获取的原因是什么，理论上所有的Request都应该统一获取

2022-06-18 08:12 UTC, sy-records commented on var/Typecho/Request.php
> -            return is_array($default) == is_array($value) ? $value : $default;
追了一下，当是多选框的时候，value的类型是array，这里逻辑有点问题，default默认值是null，所以一直返回的是default

2022-06-18 13:32 UTC, joyqi commented on var/Typecho/Request.php
> -            return is_array($default) == is_array($value) ? $value : $default;
这里主要是为了兼容getArray

2022-06-20 16:39 UTC, joyqi requested changes
两个意见

1. `getAllRequest`和`getParams`实现是重复的，前者可以通过调用后者的参数实现，建议调整
2. 可用`is_array`代替`gettype`

2022-06-21 05:59 UTC, joyqi approved these changes

2022-06-21 05:59 UTC, merged