Fix an XSS vulnerability in v1.2.1-rc
typecho/typecho pull request #1561
Opened 2023-04-14 19:11 UTC by FaithPatrick

See #1560 for more details.

2023-04-15 07:49 UTC, sy-records requested changes

2023-04-15 07:49 UTC, sy-records commented on var/Typecho/Validate.php
> +        return (bool) preg_match("/^[_a-z0-9-\.]+@([-a-z0-9]+\.)+[a-z]{2,}$/i", $str);
```suggestion
        return filter_var(filter_var($str, FILTER_SANITIZE_EMAIL), FILTER_VALIDATE_EMAIL) !== false;
```

2023-04-15 07:49 UTC, sy-records commented on var/Typecho/Validate.php
> +        !preg_match('/(\(|\)|\\\|"|<|>|[\x00-\x08]|[\x0b-\x0c]|[\x0e-\x19])/', $str);
```suggestion
        $parts = parse_url($str);
        if (!$parts) {
            return false;
        }

        return isset($parts['scheme']) &&
        in_array($parts['scheme'], ['http', 'https']) &&
        !preg_match('/(\(|\)|\\\|"|<|>|[\x00-\x08]|[\x0b-\x0c]|[\x0e-\x19])/', $str);
```

2023-04-18 13:49 UTC, joyqi commented on var/Typecho/Validate.php
> +        return (bool) preg_match("/^[_a-z0-9-\.]+@([-a-z0-9]+\.)+[a-z]{2,}$/i", $str);
Seems `FILTER_SANITIZE_EMAIL` is a filter, not a validator.

2023-04-19 00:40 UTC, sy-records commented on var/Typecho/Validate.php
> +        return (bool) preg_match("/^[_a-z0-9-\.]+@([-a-z0-9]+\.)+[a-z]{2,}$/i", $str);
yep, It can't be modified that way, I was wrong.

2023-04-20 06:24 UTC, BadApple9 approved these changes

2023-05-15 10:29 UTC, joyqi approved these changes

2023-05-15 10:29 UTC, merged