Fix assign null to property Widget\Archive::$archiveKeywords of type …
typecho/typecho pull request #1738
Opened 2024-02-23 00:38 UTC by sy-records

…string

2024-02-23 03:44 UTC, joyqi requested changes

2024-02-23 03:44 UTC, joyqi commented on var/Widget/Archive.php
> -                . htmlspecialchars($this->archiveDescription ?? $this->options->description) . '" />' . "\n";
这一段没有必要，前面已经处理过`$allows['description']`的值

2024-02-23 04:06 UTC, sy-records commented on var/Widget/Archive.php
> -                . htmlspecialchars($this->archiveDescription ?? $this->options->description) . '" />' . "\n";
对，就是直接换成`$allows['description']`了

2024-02-23 04:23 UTC, joyqi commented on var/Widget/Archive.php
> -                . htmlspecialchars($this->archiveDescription ?? $this->options->description) . '" />' . "\n";
`$allows['description']`还有开关的作用，如果传递参数`description=0`，这里的显示会不正常，最好将这两者分开处理

2024-02-23 04:23 UTC, joyqi commented on var/Widget/Archive.php
> -                . htmlspecialchars($this->archiveDescription ?? $this->options->description) . '" />' . "\n";
> 对，就是直接换成`$allows['description']`了。 一个是description，一个是twitter:description

$allows['description']还有开关的作用，如果传递参数description=0，这里的显示会不正常，最好将这两者分开处理

2024-02-23 12:03 UTC, q498419223 commented on var/Widget/Archive.php
> -                . htmlspecialchars($this->archiveDescription ?? $this->options->description) . '" />' . "\n";
Server Error错误依然存在，关键词依然不能为空啊

2024-02-26 03:52 UTC, joyqi approved these changes

2024-02-26 03:52 UTC, merged